name: IC50Prediction
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - python>=3.10,<3.11
  - numpy
  - pandas
  - scikit-learn
  - pytorch
  - transformers
  - wandb
  - pip:
    - x_transformers==1.26.2