name: IC50Prediction
channels:
  - defaults
dependencies:
  - python~=3.11.5
  - numpy
  - pandas
  - scikit-learn
  - transformers
  - wandb
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torch==2.0.0
    - torchvision
    - torchaudio
    - x_transformers==1.26.2